# Generated by Django 5.0.3 on 2024-04-15 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dndanswer',
            old_name='sequence',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='mcaanswer',
            old_name='selected_options',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='ocaanswer',
            old_name='oca_option',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='textanswer',
            old_name='text',
            new_name='answer',
        ),
    ]
