# Generated by Django 5.0.3 on 2024-04-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_sequence_dndanswer_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndanswer',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcaanswer',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocaanswer',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textanswer',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
