# Generated by Django 5.0.3 on 2024-04-15 20:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dndanswer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndanswer',
            name='updated_at',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='mcaanswer',
            name='updated_at',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ocaanswer',
            name='updated_at',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='textanswer',
            name='updated_at',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None),
        ),
    ]
