# Generated by Django 5.0.3 on 2024-04-15 20:38

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dndanswer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndanswer',
            name='answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='mcaanswer',
            name='answer',
            field=models.ManyToManyField(null=True, related_name='selected_by', to='api.mcaoption'),
        ),
        migrations.AlterField(
            model_name='ocaanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ocaoption'),
        ),
        migrations.AlterField(
            model_name='textanswer',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
