# Generated by Django 5.0.3 on 2024-04-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dndanswer_answer_alter_mcaanswer_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcaanswer',
            name='answer',
            field=models.ManyToManyField(related_name='selected_by', to='api.mcaoption'),
        ),
    ]
