# Generated by Django 5.0.3 on 2024-04-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_mcaanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dndanswer',
            name='number_of_changes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mcaanswer',
            name='number_of_changes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ocaanswer',
            name='number_of_changes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='number_of_changes',
            field=models.IntegerField(default=0),
        ),
    ]
