# Generated by Django 5.0.3 on 2024-04-15 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_surveyattempt_answers_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyattempt',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='survey_attempts', to='api.topic'),
            preserve_default=False,
        ),
    ]
