# Generated by Django 5.0.3 on 2024-04-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_surveyattempt_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyattempt',
            name='questions',
            field=models.ManyToManyField(related_name='survey_attempts', to='api.question'),
        ),
    ]
