# Generated by Django 5.0.3 on 2024-04-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_surveyattempt_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyattempt',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
