# Generated by Django 5.0.3 on 2024-04-17 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_surveyattempt_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyattempt',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_attempts', to='api.topic'),
        ),
        migrations.AlterField(
            model_name='surveyattempt',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
