# Generated by Django 5.0.3 on 2024-04-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_surveyattempt_topic_alter_surveyattempt_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dndanswer',
            old_name='created_at',
            new_name='started_at',
        ),
        migrations.RenameField(
            model_name='mcaanswer',
            old_name='created_at',
            new_name='started_at',
        ),
        migrations.RenameField(
            model_name='ocaanswer',
            old_name='created_at',
            new_name='started_at',
        ),
        migrations.RenameField(
            model_name='textanswer',
            old_name='created_at',
            new_name='started_at',
        ),
    ]
