# Generated by Django 5.0.3 on 2024-04-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_created_at_dndanswer_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dndoption',
            name='text_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dndoption',
            name='text_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dndoption',
            name='text_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dndoption',
            name='text_si',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dndoption',
            name='text_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mcaoption',
            name='text_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mcaoption',
            name='text_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mcaoption',
            name='text_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mcaoption',
            name='text_si',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mcaoption',
            name='text_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocaoption',
            name='text_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocaoption',
            name='text_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocaoption',
            name='text_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocaoption',
            name='text_si',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocaoption',
            name='text_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_hr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_si',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='name_bg',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='name_hr',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='name_hu',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='name_si',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='name_sk',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_bg',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_hr',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_hu',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_si',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_sk',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_bg',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_hr',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_hu',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_si',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_sk',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
