# Generated by Django 5.0.3 on 2024-04-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_dndoption_text_bg_dndoption_text_hr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dndoption',
            old_name='text_si',
            new_name='text_sl',
        ),
        migrations.RenameField(
            model_name='mcaoption',
            old_name='text_si',
            new_name='text_sl',
        ),
        migrations.RenameField(
            model_name='ocaoption',
            old_name='text_si',
            new_name='text_sl',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text_si',
            new_name='text_sl',
        ),
        migrations.RenameField(
            model_name='subtopic',
            old_name='name_si',
            new_name='name_sl',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='description_si',
            new_name='description_sl',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='name_si',
            new_name='name_sl',
        ),
    ]
