# Generated by Django 5.0.3 on 2024-04-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_text_si_dndoption_text_sl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textanswer',
            name='pasted',
            field=models.BooleanField(null=True),
        ),
    ]
