# Generated by Django 5.0.3 on 2024-04-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_textanswer_pasted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textanswer',
            name='pasted',
            field=models.BooleanField(default=False),
        ),
    ]
