# Generated by Django 5.0.3 on 2024-04-21 15:44

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_textanswer_pasted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('OCA', 'One Correct Answer'), ('MCA', 'Multiple Correct Answers'), ('DND', 'Drag and Drop'), ('TXT', 'Text Answer'), ('SCL', 'Scale'), ('ASG', 'Assign')], max_length=3),
        ),
        migrations.CreateModel(
            name='ASGAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None)),
                ('number_of_changes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('survey_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asg_answers', to='api.surveyattempt')),
            ],
            options={
                'verbose_name': 'ASG Answer',
                'verbose_name_plural': 'ASG Answers',
            },
        ),
        migrations.CreateModel(
            name='ASGOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('correct_position', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asg_options', to='api.question')),
            ],
            options={
                'verbose_name': 'ASG Option',
                'verbose_name_plural': 'ASG Options',
            },
        ),
        migrations.CreateModel(
            name='ScaleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None)),
                ('number_of_changes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('survey_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scl_answers', to='api.surveyattempt')),
            ],
            options={
                'verbose_name': 'Scale Answer',
                'verbose_name_plural': 'Scale Answers',
            },
        ),
    ]
