# Generated by Django 5.0.3 on 2024-04-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_question_type_asganswer_asgoption_scaleanswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScaleAnswer',
            new_name='SCLAnswer',
        ),
    ]
