# Generated by Django 5.0.3 on 2024-04-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_asgoption_text_bg_asgoption_text_cs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_en', models.ImageField(null=True, upload_to='images/')),
                ('image_cs', models.ImageField(null=True, upload_to='images/')),
                ('image_de', models.ImageField(null=True, upload_to='images/')),
                ('image_sl', models.ImageField(null=True, upload_to='images/')),
                ('image_sk', models.ImageField(null=True, upload_to='images/')),
                ('image_hr', models.ImageField(null=True, upload_to='images/')),
                ('image_hu', models.ImageField(null=True, upload_to='images/')),
                ('image_bg', models.ImageField(null=True, upload_to='images/')),
                ('name', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('name_cs', models.CharField(max_length=128, null=True)),
                ('name_de', models.CharField(max_length=128, null=True)),
                ('name_sl', models.CharField(max_length=128, null=True)),
                ('name_sk', models.CharField(max_length=128, null=True)),
                ('name_hr', models.CharField(max_length=128, null=True)),
                ('name_hu', models.CharField(max_length=128, null=True)),
                ('name_bg', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
