# Generated by Django 5.0.3 on 2024-04-21 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.question'),
            preserve_default=False,
        ),
    ]
