# Generated by Django 5.0.3 on 2024-04-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_image_image_alter_image_image_bg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name_bg',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name_cs',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name_hr',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name_hu',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name_sk',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name_sl',
        ),
    ]
