# Generated by Django 5.0.3 on 2024-04-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_image_name_remove_image_name_bg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asgoption',
            old_name='text_sl',
            new_name='text_si',
        ),
        migrations.RenameField(
            model_name='dndoption',
            old_name='text_sl',
            new_name='text_si',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_sl',
            new_name='image_si',
        ),
        migrations.RenameField(
            model_name='mcaoption',
            old_name='text_sl',
            new_name='text_si',
        ),
        migrations.RenameField(
            model_name='ocaoption',
            old_name='text_sl',
            new_name='text_si',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text_sl',
            new_name='text_si',
        ),
        migrations.RenameField(
            model_name='subtopic',
            old_name='name_sl',
            new_name='name_si',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='description_sl',
            new_name='description_si',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='name_sl',
            new_name='name_si',
        ),
    ]
