# Generated by Django 5.0.3 on 2024-04-29 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_image_image_alter_image_image_bg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asgoption',
            name='correct_position',
        ),
        migrations.CreateModel(
            name='ASGQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('correct_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asgoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asg_questions', to='api.question')),
            ],
            options={
                'verbose_name': 'ASG Question',
                'verbose_name_plural': 'ASG Questions',
            },
        ),
    ]
