# Generated by Django 5.0.3 on 2024-04-29 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_asgquestion_text_bg_asgquestion_text_cs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asganswer',
            name='answer',
        ),
        migrations.CreateModel(
            name='ASGOneAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asg_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asgquestion')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asgoption')),
            ],
            options={
                'verbose_name': 'ASG One Answer',
                'verbose_name_plural': 'ASG One Answers',
            },
        ),
        migrations.AddField(
            model_name='asganswer',
            name='answer',
            field=models.ManyToManyField(related_name='asg_answers', to='api.asgoneanswer'),
        ),
    ]
