# Generated by Django 5.0.3 on 2024-05-01 20:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_asgoneanswer_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('point', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
            ],
            options={
                'verbose_name': 'SCL Grade',
                'verbose_name_plural': 'SCL Grades',
            },
        ),
        migrations.CreateModel(
            name='GradeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grades', models.ManyToManyField(related_name='grade_types', to='api.grade')),
            ],
            options={
                'verbose_name': 'SCL GradeType',
                'verbose_name_plural': 'SCL GradeTypes',
            },
        ),
        migrations.CreateModel(
            name='SCLOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scl_questions', to='api.gradetype')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scl_questions', to='api.question')),
            ],
            options={
                'verbose_name': 'SCL Question',
                'verbose_name_plural': 'SCL Questions',
            },
        ),
    ]
