# Generated by Django 5.0.3 on 2024-05-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_grade_gradetype_scloption'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='text_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='text_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='text_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='text_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='text_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='text_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='text_sl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
