# Generated by Django 5.0.3 on 2024-05-01 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_scloption_options_alter_scloption_grade_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sclanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.grade'),
        ),
    ]
