# Generated by Django 5.0.3 on 2024-06-12 22:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_sclanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradetype',
            name='grades',
            field=models.ManyToManyField(db_index=True, related_name='grade_types', to='api.grade'),
        ),
        migrations.AlterField(
            model_name='surveyattempt',
            name='questions',
            field=models.ManyToManyField(db_index=True, related_name='survey_attempts', to='api.question'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_cs', models.CharField(max_length=255, null=True)),
                ('title_de', models.CharField(max_length=255, null=True)),
                ('title_sl', models.CharField(max_length=255, null=True)),
                ('title_sk', models.CharField(max_length=255, null=True)),
                ('title_hr', models.CharField(max_length=255, null=True)),
                ('title_hu', models.CharField(max_length=255, null=True)),
                ('title_bg', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_cs', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
                ('description_sl', models.TextField(null=True)),
                ('description_sk', models.TextField(null=True)),
                ('description_hr', models.TextField(null=True)),
                ('description_hu', models.TextField(null=True)),
                ('description_bg', models.TextField(null=True)),
                ('sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.subtopic')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('actual_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_results', to='api.rating')),
                ('sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_results', to='api.subtopic')),
            ],
            options={
                'verbose_name': 'Survey result',
                'verbose_name_plural': 'Survey results',
            },
        ),
        migrations.AddField(
            model_name='surveyattempt',
            name='survey_result',
            field=models.ManyToManyField(related_name='survey_attempts', to='api.surveyresult'),
        ),
    ]
