# Generated by Django 5.0.3 on 2024-06-13 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_gradetype_grades_alter_surveyattempt_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='type',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
            preserve_default=False,
        ),
    ]
