# Generated by Django 5.0.3 on 2024-06-13 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_rating_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='actual_subpoints',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
            preserve_default=False,
        ),
    ]
