# Generated by Django 5.0.3 on 2024-06-13 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_surveyresult_actual_subpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresult',
            name='actual_subpoints',
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='actual_points',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
