# Generated by Django 5.0.3 on 2024-06-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_surveyresult_actual_subpoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asgoption',
            name='text_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asgquestion',
            name='text_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dndoption',
            name='text_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='text_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_sr',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='mcaoption',
            name='text_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocaoption',
            name='text_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='evaluated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='description_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='name_sr',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_sr',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_sr',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
