# Generated by Django 5.0.3 on 2024-06-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_asgoption_text_sr_asgquestion_text_sr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asgoption',
            name='text_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asgquestion',
            name='text_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dndoption',
            name='text_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='text_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_bs',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='mcaoption',
            name='text_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocaoption',
            name='text_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='description_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='title_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='name_bs',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_bs',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_bs',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
