# Generated by Django 5.0.7 on 2024-08-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_asgoption_text_bs_asgquestion_text_bs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='can_be_none',
            field=models.BooleanField(default=False),
        ),
    ]
