# Generated by Django 5.0.7 on 2024-08-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_question_options_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
