# Generated by Django 5.0.8 on 2024-09-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_bg',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_bs',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_cs',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_de',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_en',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_hr',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_hu',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_sk',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_sl',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_sr',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
