services:
  ## Postgres
  postgresql:
    container_name: integrage-postgresql
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=integrage 
    volumes:
      - postgresql_data:/bitnami/postgresql
      - postgresql_pre_initdb:/docker-entrypoint-preinitdb.d
      - postgresql_initdb:/docker-entrypoint-initdb.d
    ports:
      - '127.0.0.1:5432:5432'

  ## Backend
  backend:
    build: backend
    container_name: integrage-backend
    volumes:
      - ./backend:/backend
    environment:
      - DJANGO_BASE_URL=http://localhost:8080
      - DJANGO_ALLOWED_HOSTS=localhost,webapp,10.0.0.16,192.168.1.2,backend
      - DJANGO_DB_NAME=integrage
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=postgres
      - DJANGO_DB_HOST=postgresql
      - DJANGO_DB_PORT=5432
      - DJANGO_EMAIL_HOST=smtp.office365.com
      - DJANGO_EMAIL_PORT=587
      - DJANGO_EMAIL_USE_TLS=true
      - DJANGO_EMAIL_HOST_USER=integrage@hotmail.com
      - DJANGO_EMAIL_HOST_PASSWORD=${DJANGO_EMAIL_HOST_PASSWORD}
      - DJANGO_EMAIL_FROM=integrage@hotmail.com
      - DJANGO_SECRET=${DJANGO_SECRET}
      - DJANGO_CRYPTO_KEY=${DJANGO_CRYPTO_KEY}
      - DJANGO_CRYPTO_SALT=${DJANGO_CRYPTO_SALT}

  ## Frontend
  frontend:
    build: frontend
    container_name: integrage-frontend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - VITE_WEBSITE_URL=http://localhost:8080

  ## NGINX
  edge:
    build:
      context: edge
      dockerfile: Dockerfile
    container_name: integrage-edge
    ports:
      - '8080:8080'
    volumes:
      - ./edge/integrage.conf:/opt/bitnami/nginx/conf/server_blocks/integrage.conf:ro
      - ./backend/media:/app/media
      - ./backend/staticfiles:/app/static
    depends_on:
      - frontend
      - backend  

volumes:
  node_modules:
    driver: local
  postgresql_data:
    driver: local
  postgresql_initdb:
    driver: local
  postgresql_pre_initdb:
    driver: local