services:
  ## Postgres
  postgresql:
    container_name: integrage-postgresql-prod
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@{POSTGRES_PASSWORD}
      - POSTGRES_DB=integrage 
    volumes:
      - postgresql_data:/bitnami/postgresql
      - postgresql_pre_initdb:/docker-entrypoint-preinitdb.d
      - postgresql_initdb:/docker-entrypoint-initdb.d
    ports:
      - '127.0.0.1:5432:5432'
    restart: always

  ## Backend
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    container_name: integrage-backend-prod
    volumes:
      - ./backend:/backend
    environment:
      - DJANGO_PRODUCTION=true
      - DJANGO_BASE_URL=https://satool.ujep.cz
      - DJANGO_ALLOWED_HOSTS=localhost,webapp,10.0.0.16,backend,satool.ujep.cz
      - DJANGO_DB_NAME=integrage
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=@{POSTGRES_PASSWORD}
      - DJANGO_DB_HOST=postgresql
      - DJANGO_DB_PORT=5432
      - DJANGO_EMAIL_HOST=xxx
      - DJANGO_EMAIL_PORT=xxx
      - DJANGO_EMAIL_USE_TLS=true
      - DJANGO_EMAIL_HOST_USER=xxx
      - DJANGO_EMAIL_HOST_PASSWORD=${DJANGO_EMAIL_HOST_PASSWORD}
      - DJANGO_EMAIL_FROM=xxx
      - DJANGO_SECRET=${DJANGO_SECRET}
      - DJANGO_CRYPTO_KEY=${DJANGO_CRYPTO_KEY}
      - DJANGO_CRYPTO_SALT=${DJANGO_CRYPTO_SALT}
    restart: always

  ## Frontend
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_WEBSITE_URL: https://satool.ujep.cz
    container_name: integrage-frontend-prod
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: always

  ## NGINX
  edge:
    build:
      context: edge
      dockerfile: Dockerfile
    container_name: integrage-edge-prod
    ports:
      - '8080:8080'
    volumes:
      - ./edge/integrage.conf:/opt/bitnami/nginx/conf/server_blocks/integrage.conf:ro
      - ./backend/media:/app/media
      - ./backend/staticfiles:/app/static
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  postgresql_data:
    driver: local
  postgresql_initdb:
    driver: local
  postgresql_pre_initdb:
    driver: local